# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56da18ab9d80939cb90dc89bb1d1044f914a936427b416ded909095e694937f901a6fa80842cbf00bd32c8f986045d6cc334cd38f5783328e8a8eb5f1afee63a

test:
  secret_key_base: baf2e56b5627aa130c5ae3ed8a3df4d8cdfb6de9a206059add115cffb3a3ec7e418a9622a77d3609bcac39c80cf38850069597b23cf9e08d8bde4f56fc909149

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
